# Generated by Django 2.0.3 on 2018-05-19 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlphaChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.IntegerField(default=0)),
                ('owner', models.IntegerField(default=1)),
                ('private', models.BooleanField(default=False)),
                ('admin_only', models.BooleanField(default=False)),
            ],
        ),
    ]
