KITE_USER_ID = "ZZ8276"
KITE_API_KEY = "8sawti1bam50o624"
KITE_API_SECRET = "oum6c2bnqtnhz1os5qmz6saaz7yxxts1"
KITE_INSTRUMENTS_URL = "https://api.kite.trade/instruments"
KITE_EQ_MARGIN_URL = "https://api.kite.trade/margins/equity"
NIFTY_FO_URL = "https://www.nseindia.com/content/fo/fo_mktlots.csv"
